### ISSUE TITLE
Is this project open for contributions?

### ISSUE THREAD

**Issue by ghost** [haxpor/sdl2-manpage#3]
Hi, I'd like to complete some of the man pages. For instance the remark section of [SDL_AddTimer](https://github.com/haxpor/sdl2-manpage/blob/a0494f232a551e66a4f08ff4d54c1e65bd5d8dcf/src/SDL_AddTimer.3) is empty.

Would you mind if I worked on it?

Also I thought I should inform you that I've published an arch linux package of your repo [here](https://aur.archlinux.org/packages/sdl2-manpage-git/).

**Comment by haxpor** [comment]
Hey taigah! Please feel free to do so. Any missing pages are very welcome for you or anyone to work on.
Also make sure to add any API or things you have covered in `COVER.md`.

Thank you for taking an initiative on maintaining the arch package. No problem at all :)
 
PS: I closed this for now, but if there's anything else, please feel free to continue discussing further here.
 
**Edit**:
Yeah, some of the missing info in particular section is due to that time the upstream SDL documentation also misses info. By now, upstream should be updated so it's good thing you notice that!

**Comment by haxpor** [comment]
*FYI*: I have now also published on PPA namely `sdl2-manpage`. Also updated `REAMD.md` as such. Each update will built from tag marked properly via git (now it has a tag `v0.1.6`).

Whenever @taigah  have a gap of time, please feel free to update `README.md` to include how to install AUR package, I'm happy to merge later :) or you can let me know here, I will make changes on my side. Thanks.

*Edit*:
I asked this because I'm not quite confident whether the commands (as I can research) would be correct and work as expected, as I didn't use arch myself.
